//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class suscriptor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public suscriptor()
        {
            this.suscripcion = new HashSet<suscripcion>();
        }
    
        public int idsuscriptor { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int numerodocumento { get; set; }
        public string mail { get; set; }
        public string direccion { get; set; }
        public string usuario { get; set; }
        public string passowrd { get; set; }
        public string tipodoc { get; set; }
        public string telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<suscripcion> suscripcion { get; set; }
    }
}
