//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class suscripcion
    {
        public int idasociacion { get; set; }
        public int idsuscriptor { get; set; }
        public Nullable<System.DateTime> fechaalta { get; set; }
        public Nullable<System.DateTime> fechabaja { get; set; }
        public string motivo { get; set; }
    
        public virtual suscriptor suscriptor { get; set; }
    }
}
